markdown: kramdown
safe: false
baseurl: /
exclude:
  - README.md

blog:
    host: wilsonis.github.io/
    name: 博科模型手板

custom:
    category:
        thinking: Why...
        experience: How To Do
        discovery: What's New
        criticism: What's Wrong
        communication: Sharing
    categories:
      - name:  首页
        title: 首页

      - name:  产品介绍
        title: 产品介绍

      - name:  关于我们
        title: 关于我们



meta:
    author:
        name: wilsonIsOnly
        email: zhangtao522009@163.com
        github: wilsonIs                            # GitHub账号

